name: Update and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # Manual trigger with optional input parameters
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual update'

# Add permissions needed for the workflow
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-semesters:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run update_semesters.py
      run: python scripts/update_semesters.py

  deploy:
    needs: update-semesters
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist